import Head from 'next/head';
import Sidebar from '../components/Sidebar.js';

export default function Home() {
  return (
    <div>
      <Head>
        <title>MVP</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Sidebar />
    </div>
  );
}
